/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/pi/ros_workspace/src/tetrix_motors/msg/MotorCommand.msg
 *
 */


#ifndef TETRIX_MOTORS_MESSAGE_MOTORCOMMAND_H
#define TETRIX_MOTORS_MESSAGE_MOTORCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tetrix_motors
{
template <class ContainerAllocator>
struct MotorCommand_
{
  typedef MotorCommand_<ContainerAllocator> Type;

  MotorCommand_()
    : run_time(0.0)
    , motor_names()
    , motor_speeds()
    , motor_accelerations()  {
    }
  MotorCommand_(const ContainerAllocator& _alloc)
    : run_time(0.0)
    , motor_names(_alloc)
    , motor_speeds(_alloc)
    , motor_accelerations(_alloc)  {
    }



   typedef float _run_time_type;
  _run_time_type run_time;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _motor_names_type;
  _motor_names_type motor_names;

   typedef std::vector<int8_t, typename ContainerAllocator::template rebind<int8_t>::other >  _motor_speeds_type;
  _motor_speeds_type motor_speeds;

   typedef std::vector<int8_t, typename ContainerAllocator::template rebind<int8_t>::other >  _motor_accelerations_type;
  _motor_accelerations_type motor_accelerations;




  typedef boost::shared_ptr< ::tetrix_motors::MotorCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tetrix_motors::MotorCommand_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct MotorCommand_

typedef ::tetrix_motors::MotorCommand_<std::allocator<void> > MotorCommand;

typedef boost::shared_ptr< ::tetrix_motors::MotorCommand > MotorCommandPtr;
typedef boost::shared_ptr< ::tetrix_motors::MotorCommand const> MotorCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tetrix_motors::MotorCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tetrix_motors::MotorCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tetrix_motors

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'tetrix_motors': ['/home/pi/ros_workspace/src/tetrix_motors/msg'], 'std_msgs': ['/opt/ros/groovy/share/std_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tetrix_motors::MotorCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tetrix_motors::MotorCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tetrix_motors::MotorCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tetrix_motors::MotorCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tetrix_motors::MotorCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tetrix_motors::MotorCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tetrix_motors::MotorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "831d9cb0d2fac073c1d0cfa479541f07";
  }

  static const char* value(const ::tetrix_motors::MotorCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x831d9cb0d2fac073ULL;
  static const uint64_t static_value2 = 0xc1d0cfa479541f07ULL;
};

template<class ContainerAllocator>
struct DataType< ::tetrix_motors::MotorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tetrix_motors/MotorCommand";
  }

  static const char* value(const ::tetrix_motors::MotorCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tetrix_motors::MotorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 run_time\n\
string[] motor_names\n\
int8[] motor_speeds\n\
int8[] motor_accelerations\n\
\n\
\n\
";
  }

  static const char* value(const ::tetrix_motors::MotorCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tetrix_motors::MotorCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.run_time);
      stream.next(m.motor_names);
      stream.next(m.motor_speeds);
      stream.next(m.motor_accelerations);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MotorCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tetrix_motors::MotorCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tetrix_motors::MotorCommand_<ContainerAllocator>& v)
  {
    s << indent << "run_time: ";
    Printer<float>::stream(s, indent + "  ", v.run_time);
    s << indent << "motor_names[]" << std::endl;
    for (size_t i = 0; i < v.motor_names.size(); ++i)
    {
      s << indent << "  motor_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.motor_names[i]);
    }
    s << indent << "motor_speeds[]" << std::endl;
    for (size_t i = 0; i < v.motor_speeds.size(); ++i)
    {
      s << indent << "  motor_speeds[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.motor_speeds[i]);
    }
    s << indent << "motor_accelerations[]" << std::endl;
    for (size_t i = 0; i < v.motor_accelerations.size(); ++i)
    {
      s << indent << "  motor_accelerations[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.motor_accelerations[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TETRIX_MOTORS_MESSAGE_MOTORCOMMAND_H
